const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

module.exports = {
    //mode: 'jit',
    purge: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],
    darkMode: 'class', // or false or 'media' or 'class'
    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
        colors: {
            // Build your palette here
            primary:    colors.indigo,
            secondary:  colors.rose,
            // Default palette here
            transparent:'transparent',
            current:    'currentColor',
            black:      'black',
            white:      'white',
            blueGray:   colors.blueGray,
            coolGray:   colors.coolGray,
            gray:       colors.gray,
            trueGray:   colors.trueGray,
            warmGray:   colors.warmGray,
            red:        colors.red,
            orange:     colors.orange,
            amber:      colors.amber,
            yellow:     colors.yellow,
            lime:       colors.lime,
            green:      colors.green,
            emerald:    colors.emerald,
            teal:       colors.teal,
            cyan:       colors.cyan,
            sky:        colors.sky,
            blue:       colors.sky,
            indigo:     colors.indigo,
            violet:     colors.violet,
            purple:     colors.purple,
            fuchsia:    colors.fuchsia,
            pink:       colors.pink,
            rose:       colors.rose,
        }
    },

    variants: {
        extend: {
            accessibility: ['responsive', 'focus-within', 'focus'],
            alignContent: ['responsive'],
            alignItems: ['responsive'],
            alignSelf: ['responsive'],
            animation: ['responsive'],
            appearance: ['responsive'],
            backdropBlur: ['responsive'],
            backdropBrightness: ['responsive'],
            backdropContrast: ['responsive'],
            backdropDropShadow: ['responsive'],
            backdropFilter: ['responsive'],
            backdropGrayscale: ['responsive'],
            backdropHueRotate: ['responsive'],
            backdropInvert: ['responsive'],
            backdropSaturate: ['responsive'],
            backdropSepia: ['responsive'],
            backgroundAttachment: ['responsive'],
            backgroundBlendMode: ['responsive'],
            backgroundClip: ['responsive'],
            backgroundColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus', 'active', 'checked', 'disabled'],
            backgroundImage: ['responsive'],
            backgroundOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus', 'disabled'],
            backgroundPosition: ['responsive'],
            backgroundRepeat: ['responsive'],
            backgroundSize: ['responsive'],
            backgroundOrigin: ['responsive'],
            blur: ['responsive'],
            borderCollapse: ['responsive'],
            borderColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus', 'checked', 'active'],
            borderOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus', 'checked', 'active'],
            borderRadius: ['responsive', 'first', 'last'],
            borderStyle: ['responsive'],
            borderWidth: ['responsive'],
            boxDecorationBreak: ['responsive'],
            boxShadow: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
            boxSizing: ['responsive'],
            brightness: ['responsive'],
            clear: ['responsive'],
            container: ['responsive'],
            contrast: ['responsive'],
            cursor: ['responsive'],
            display: ['responsive'],
            divideColor: ['responsive', 'dark'],
            divideOpacity: ['responsive', 'dark'],
            divideStyle: ['responsive'],
            divideWidth: ['responsive'],
            dropShadow: ['responsive'],
            fill: ['responsive'],
            filter: ['responsive'],
            flex: ['responsive'],
            flexDirection: ['responsive'],
            flexGrow: ['responsive'],
            flexShrink: ['responsive'],
            flexWrap: ['responsive'],
            float: ['responsive'],
            fontFamily: ['responsive'],
            fontSize: ['responsive'],
            fontSmoothing: ['responsive'],
            fontStyle: ['responsive'],
            fontVariantNumeric: ['responsive'],
            fontWeight: ['responsive'],
            gap: ['responsive'],
            gradientColorStops: ['responsive', 'dark', 'hover', 'focus'],
            grayscale: ['responsive'],
            gridAutoColumns: ['responsive'],
            gridAutoFlow: ['responsive'],
            gridAutoRows: ['responsive'],
            gridColumn: ['responsive'],
            gridColumnEnd: ['responsive'],
            gridColumnStart: ['responsive'],
            gridRow: ['responsive'],
            gridRowEnd: ['responsive'],
            gridRowStart: ['responsive'],
            gridTemplateColumns: ['responsive'],
            gridTemplateRows: ['responsive'],
            height: ['responsive'],
            hueRotate: ['responsive'],
            inset: ['responsive'],
            invert: ['responsive'],
            isolation: ['responsive'],
            justifyContent: ['responsive'],
            justifyItems: ['responsive'],
            justifySelf: ['responsive'],
            letterSpacing: ['responsive'],
            lineHeight: ['responsive'],
            listStylePosition: ['responsive'],
            listStyleType: ['responsive'],
            margin: ['responsive'],
            maxHeight: ['responsive'],
            maxWidth: ['responsive'],
            minHeight: ['responsive'],
            minWidth: ['responsive'],
            mixBlendMode: ['responsive'],
            objectFit: ['responsive'],
            objectPosition: ['responsive'],
            opacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
            order: ['responsive'],
            outline: ['responsive', 'focus-within', 'focus', 'hover', 'active', 'checked', 'dark'],
            overflow: ['responsive'],
            overscrollBehavior: ['responsive'],
            padding: ['responsive'],
            placeContent: ['responsive'],
            placeItems: ['responsive'],
            placeSelf: ['responsive'],
            placeholderColor: ['responsive', 'dark', 'focus'],
            placeholderOpacity: ['responsive', 'dark', 'focus'],
            pointerEvents: ['responsive'],
            position: ['responsive'],
            resize: ['responsive'],
            ringColor: ['responsive', 'dark', 'focus-within', 'focus', 'hover', 'active'],
            ringOffsetColor: ['responsive', 'dark', 'focus-within', 'focus', 'hover', 'active'],
            ringOffsetWidth: ['responsive', 'focus-within', 'focus', 'hover', 'active'],
            ringOpacity: ['responsive', 'dark', 'focus-within', 'focus', 'hover', 'active'],
            ringWidth: ['responsive', 'focus-within', 'focus', 'hover', 'active'],
            rotate: ['responsive', 'hover', 'focus'],
            saturate: ['responsive'],
            scale: ['responsive', 'hover', 'focus', 'active', 'checked'],
            sepia: ['responsive'],
            skew: ['responsive', 'hover', 'focus', 'active', 'checked'],
            space: ['responsive'],
            stroke: ['responsive'],
            strokeWidth: ['responsive'],
            tableLayout: ['responsive'],
            textAlign: ['responsive'],
            textColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus', 'active', 'checked', 'disabled'],
            textDecoration: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus', 'active', 'checked'],
            textOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
            textOverflow: ['responsive'],
            textTransform: ['responsive'],
            transform: ['responsive'],
            transformOrigin: ['responsive'],
            transitionDelay: ['responsive'],
            transitionDuration: ['responsive'],
            transitionProperty: ['responsive'],
            transitionTimingFunction: ['responsive'],
            translate: ['responsive', 'hover', 'focus'],
            userSelect: ['responsive'],
            verticalAlign: ['responsive'],
            visibility: ['responsive'],
            whitespace: ['responsive'],
            width: ['responsive'],
            wordBreak: ['responsive'],
            zIndex: ['responsive', 'focus-within', 'focus']
        },
    },

    plugins: [
        require('@tailwindcss/forms'),
    ],
};
